### ISSUE TITLE
Support for PROJ 6.0.0

### ISSUE THREAD

**Issue by sebastic** [therion/therion#130]
Therion still uses `proj_api.h` which is deprecated in PROJ 6.0.0 and will be removed in PROJ 7.0.0 (scheduled for March 2020).

When using `proj_api.h` with PROJ 6.0.0 `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` needs to be added to `CFLAGS` to prevent a compiler error.

Therion should be updated to (also) support the `proj.h` API.

**Comment by mbudaj** [comment]
Support for new proj.h API is already implemented locally, but needs a lot
of testing before publishing it.
Martin

**Comment by sebastic** [comment]
Thanks for the update, are the changes available in a public branch somewhere?

Once the changes are in master we can update the status for Therion in the [adoption status list](https://github.com/OSGeo/proj.4/wiki/proj.h-adoption-status) maintained by the PROJ community.

**Comment by mbudaj** [comment]
Implemented in 13646f08caed4ba5011b108512566aad548a417d.

**Comment by mbudaj** [comment]
> Once the changes are in master we can update the status for Therion in the [adoption status list](https://github.com/OSGeo/proj.4/wiki/proj.h-adoption-status) maintained by the PROJ community.

The status may be updated again, proj.h API is supported in the release 5.4.4.

**Comment by speleo3** [comment]
Should this ticket be reopened, given the [missing pipelines support in PROJ 6](https://github.com/OSGeo/PROJ/issues/1619)?

**Comment by hbeni** [comment]
Hi there,
i still have problems with debian sid (bullseye), i cannot compile any project if there is a cs definition somewhere. The upcoming debian release uses PROJ6.
I'm using `therion 5.4.4 (2019-05-01)` from the debian package 5.4.4ds1-2, however the same issue arised in the beginning of october when compiling manually from the git branch.

The ticket here states that there is already support for proj6; how can i enable this?

Details are in the mailing list already: https://mailman.speleo.sk/pipermail/therion/2019-September/007773.html, including a [Testcase](https://mailman.speleo.sk/pipermail/therion/2019-September/007776.html).

-----
```
beni@segin:~/therion/$ therion test.thconf
therion 5.4.4 (2019-05-01)
cavern - Survex 1.2.42
initialization file: /etc/therion.ini
reading ... done
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdfetex)
 restricted \write18 enabled.
entering extended mode
(./fonttest.tex
checking optional fonts csr10 csti10 csbx10 csss10 csssi10 ... NOT INSTALLED
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdfetex)
 restricted \write18 enabled.
entering extended mode
(./fonttest.tex
checking optional fonts cmcyr10 cmcti10 cmcbx10 cmcss10 cmcssi10 ... NOT INSTALLED
configuration file: therion/plan.DOP.map.thconfig
reading ... done
reading source files ... proj_create: Error -1: no arguments in initialization list

therion: error -- PROJ4 library: -1 (no arguments in initialization list)
```
Testcase:
```
---------test.th-------------
survey test
   centerline
     units length meters
     data normal from to length bearing clino
     1   2       10      10      10
     2   3       20      20      20

    cs EPSG:31258
    fix 1 470000 200000 123

   endcenterline
endsurvey
------------------------------

---------test.thconf-------------
source test.th

export model -o test.3d
---------------------------------
```

**Comment by speleo3** [comment]
@hbeni did you try after #151 had been merged on October 13?

**Comment by hbeni** [comment]
> @hbeni did you try after #151 had been merged on October 13?

Yes, however i think i made an error while doing it. I trid it again now and it works :)
Thank you! Issue is fixed for me too!

Therion is such a great tool!
