### ISSUE TITLE
Therion book needs "break" defined correctly for map-of-maps

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#146]
The "break" command is shown in the Therion book within the "map" syntax section and then also within the  "displaying overlaying maps in offset" section. In both cases, it is shown as applying both to a "map" containing "scraps", and a "map" containing "maps".

In reality, it applies only to a map made from scraps. When a map is made from maps, an implicit break is automatically applied between each map. The book does not make this clear, and uses "break" within a map of maps in the "displaying overlaying maps in offset" section (a place where it will have no effect and is not needed).

The book should explicitly state that when a map is made from maps, that a break is automatically applied between child maps. The book should explicitly state (in the "break" definition) that it only applies to scraps. The book should not use "break" in the "displaying overlaying maps in offset" section between child maps.

**Comment by hbeni** [comment]
What about this change:
Page 29:
![grafik](https://user-images.githubusercontent.com/13608602/70165400-24335880-16c3-11ea-85ff-92108168f3af.png)


Page 30:
![grafik](https://user-images.githubusercontent.com/13608602/70165366-17166980-16c3-11ea-8dc8-935d0d4c8a84.png)


> "break" in the "displaying overlaying maps in offset" 
where is that? could not find it in current git...

**Comment by tarquinwj** [comment]
Those changes look great to me.

https://therion.speleo.sk/downloads/thbook.pdf
search for: Dipsplaying overlaying maps in offset
page 95.

I can't see where this is defined in the source though.

**Comment by hbeni** [comment]
Ah thats added by the examples i think.

**Comment by hbeni** [comment]
> https://therion.speleo.sk/downloads/thbook.pdf
> search for: Dipsplaying overlaying maps in offset page 95.

Is already fixed in git source.

**Comment by hbeni** [comment]
Here you go, that patch fixes this issue:
[0001-Thbook-add-details-to-break-in-map-documentation-fix.patch.txt](https://github.com/therion/therion/files/3923466/0001-Thbook-add-details-to-break-in-map-documentation-fix.patch.txt)
