### ISSUE TITLE
Sql export: Store length data in SHOT table with one more decimal

### ISSUE THREAD

**Issue by finnesand** [therion/therion#147]
Today, LENGTH, ADJ_LENGTH and ERR_LENGTH (SHOT table) are stored with two decimals (= cm) cm. Can you change it to three decimals (= mm)?

The reason is that data from PocketTopo has three decimals. And those data are, more or less, stored in the SHOT table.

And I think three decimals makes more sense since BEARING and GRADIENT has two.

(Perhaps the coordinates in the STATION table could have three decimals as well.)

**Comment by hbeni** [comment]
I think that this values get rounded correctly.
Does it make sense to give a fraction of a millimeter in the length? I would say no, because the expected error from the measurement will most probably be bigger than this - i somewhere have read that DistoX accuracy is within 3mm for length measurements (and below 0.5° for bearing and gradient)...

**Comment by finnesand** [comment]
Yes, the expected error must be much bigger. But it is somewhat easier to find the original splay in PocketTopo if the database use mm. The problem occurs for very short splays, since the Therion txt export from PocketTopo change the azimuth and clino values. The attached file shows some examples. The changes are larger for subvertical splays. For instance the therion txt file (not enclosed) has changed the azi from 10 to 18,43 deg. for a splay that is 0,1 meter and clino is 88 deg.

Of course, even though these changes are annoying, they are not at all important. Heeb said: "However, be aware that the resulting precision of the vectors is still 1mm, even if the numbers look quite different. This is far enough for cave surveying, especially for splay shots."

![Short splays](https://user-images.githubusercontent.com/8087572/78702582-1a3b9380-7909-11ea-956c-813ce559f226.JPG)

**Comment by hbeni** [comment]
So to summarize, this is a cosmetic feature request?
The goal here is to be able to better relate the sql data to the original input?

**Comment by finnesand** [comment]
Yes, cosmetic feature request. I hoped it was simple to increase with one decimal.

And yes, the main problem is the therion export from PocketTopo. If I understand Heeb correct, also splays are converted from polar to rectangular, averaged if necessary, and converted back. The precision used for the vectors is 1 mm.

**Comment by hbeni** [comment]
Maybe you should go to pocketTopo developers to get this fixed?

**Comment by finnesand** [comment]
Heeb preferred to keep it as it was. But even if he fix it, I suggest that Therion stores the length with one more decimal in the SQL database, if its simple to do that change.

**Comment by hbeni** [comment]
I want to point out that the data in the SQL database export is processed data, that is also a source for the data not corresponding to the input data.

That said, i am not familiar enough with therions source so maybe stacho needs to have a look at this.

**Comment by finnesand** [comment]
That's fine. 

BEARING (SHOT table) is corrected for mag declination, that's good. LENGTH and GARDIENT has the same values as in the th-files. Thats good as well. (I hope the SHOT table stores data in one format, so that measurements in 400 deg are converted to 360. But I haven't checked that.)

The sql database is interesting. I think it is possible to do different kinds of analysis, in particular in the future.

**Comment by hbeni** [comment]
> The sql database is interesting. I think it is possible to do different kinds of analysis, in particular in the future.
It is! I usually load it into a sqlite3 database and run queries there.

**Comment by smudrak** [comment]
Adding one more digit do output is really simple, sorry it took so long. Today closing old issues and starting from the easiest to implement.
