### ISSUE TITLE
Add thconfig option to disable offsets

### ISSUE THREAD

**Issue by hbeni** [therion/therion#159]
I want to propose another thconfig option to disable offset printing.
With recent therion versions, i can use the `maps off` thconfig command to disable map parsing alltogether.
However this poses the problem, that i cannot render `preview above` or `preview below` map parts anymore as these are selected/defined with map structures.

It would be very good to have another option to the `maps` command like `maps no-offset` to just disable offset printing but preserve all other aspects (or a new command alltogether?).

----
I have no clue on therion internals, but maybe this could be achieved with just treating the option like defining all offsets as positioned at `<mapname> [0 0 m] none`? The "none" part is already present in `map-level`command if preview map level is out of scope.

**Comment by smudrak** [comment]
It should be working now, so closing the issue. @hbeni, could you please check "maps-offset off" feature whether it is working as required? Thanks.

**Comment by hbeni** [comment]
Works like a charm!
Thank you very much! :)
