### ISSUE TITLE
Need a way to make maps take on the colour range for another map

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#166]
Case 1: Doing a zoomed-in section of a cave within a larger system. When using "color map-fg altitude" for the entire map, and wanting the zoomed in section (eg. map of the entrance series only) to have the same altitude colours as it did in the main map. By default, Therion will use the 7 colour rainbow for the highest to lowest parts of the cave that are being displayed, so the colours will not match.

Case 2: doing cross sections of multiple passages, when rendering the multiple cross sections as a projected elevation (one of the easiest ways to do accurate multiple-passage cross sections). The passages in the cross section can have the same colours as they do in the plan view to help identification.

Currently, the only way to achieve this is with an altitude lookup table, which requires manual knowledge of the range of the system, so it needs to be altered every time new cave is found.

The ideal solution would be an option, like:
fg-altitude-map somemapMP@mycave
select adifferentmapMP@mycave
This would take the colouring bands from somemapMP@mycave, and apply them when rendering adifferentmapMP@mycave.

**Comment by CaverBruce** [comment]
This would be good for building in automation (your case 1) to future proof a mapping project where a large but unknown magnitude of change in vertical range might be expected at some future date.  Or if the range of the system is changing with every survey trip.
My experience so far is that the highest possible extent and lowest likely extent of the cave is known well in advance.  Therefore a manual lookup is just fine.
Also a manual lookup ensures that nice round numbers appear in the colour legend.  For me the random and changing numbers in the colour legend are the more irritating characteristic, not to mention always having to have a seven stage legend.  So for me the manual use of the existing lookup feature is a preferred solution that in most scenarios gives nice controllable and stable output coloration that can be replicated for overview and sub-maps.
Not a reason not to add this feature though.   I have not played with sections enough to remember how well they behave with altitude colours.

**Comment by tarquinwj** [comment]
I think in a hazy dream last night (OK, it's still basically night, but I woke up early), I found the solution.
All you would need, is to include the surveys in your map, then use "symbol-hide group centreline" to hide them from the render, so the map looks like this:
map foo
  subsectionmap@subsection
  othersubsection
  anothersubsection
endmap
(Or if you need the centreline for some centreline-only section of the survey within the part you are trying to isolate, you would need to include a scrap or two containing any single survey station and no other symbols from the highest and lowest parts of the cave, and then use -attr to select and hide those stations again. Once a single station is included from a survey, the whole survey gets used in the altitude calculations.)

This is actually not clumsy at all, but it needs to be documented on the wiki somewhere, because it is like magic that it even works. And I don't think anyone on the list knew that there was a solution.

So I think this can be resolved wontfix - the functionality is already there, just hard to find.

**Comment by tarquinwj** [comment]
> the highest possible extent and lowest likely extent of the cave is known well in advance

For the systems we are currently mapping, the highest point in the cave is known only in a single case, and the lowest point is known only in a (different) single case, because we are still exploring those systems, so having to manually update a lookup is a pain. So yes, future proofing is indeed my reason for asking.

> a manual lookup ensures that nice round numbers appear in the colour legend

It always uses rounded numbers anyway (something else I need to document on the wiki). But I get what you mean; 10, 20, 30 looks nicer than 11, 20, 29.

> I have not played with sections enough to remember how well they behave with altitude colours.

True cross section scraps take on the colour of the regular scrap that they are attached to (unless you specifically tell them not to have any colour). Which is great! Except that when doing cross sections of multiple passages at once, there is no way to get it to get the colours right for each passage, except rendering it as a projected elevation. I will be updating my wiki article, because this is finally a complete solution :)

**Comment by CaverBruce** [comment]
> It always uses rounded numbers anyway (something else I need to document on the wiki). But I get what you mean; 10, 20, 30 looks nicer than 11, 20, 29.

Hmm, don't believe I have ever seen Therion colour scale use numbers rounded to other than the nearest 1m.
![image](https://user-images.githubusercontent.com/19825868/70383845-fb200a00-19d9-11ea-92d9-fa55e30d1bf9.png)
Has this been adjusted in a recent update?

**Comment by tarquinwj** [comment]
On 08/12/2019 03:46, Bruce wrote:
>     It always uses rounded numbers anyway (something else I need to
>     document on the wiki). But I get what you mean; 10, 20, 30 looks
>     nicer than 11, 20, 29.
> 
> Hmm, don't believe I have ever seen Therion colour scale use numbers
> rounded to other than the nearest 1m.

That's what I mean; it rounds to the nearest integer (which I have now
documented on the wiki. But with your lookup table, you can make it use
nicer numbers like "10, 20, 30".
