### ISSUE TITLE
Problem with "line water-flow" after "-flip horizontal"

### ISSUE THREAD

**Issue by libormatuska** [therion/therion#245]
Before `-flip horizontal` object `line water-flow` looks OK (water flows down) - see map:

[Hospoda_Projection_extended_Map - pred flipem.pdf](https://github.com/therion/therion/files/4764524/Hospoda_Projection_extended_Map.-.pred.flipem.pdf)

After `-flip horizontal` object `line water-flow` looks wrongly (water flows up) - see map:
Parameter `reverse` is not changed.

[Hospoda_Projection_extended_Map.pdf](https://github.com/therion/therion/files/4764532/Hospoda_Projection_extended_Map.pdf)

**Comment by CaverBruce** [comment]
This message also describes the same problem.

https://www.mail-archive.com/therion@speleo.sk/msg06576.html

Flip functionality needs some debugging.

 

Bruce

**Comment by smudrak** [comment]
Looks to me, that disabling flipping reversion of line arrow, gradient and waterflow should fix the problem.

**Comment by CaverBruce** [comment]
Thanks Stacho, a long awaited fix!
I've a few historic projects to work through to see how effective this has been, and no doubt patching up the reverse status on some lines.  Seem to recall there might have been issues with points.  I'll check over the next few weeks and get back if there is.  Thanks again, much appreciated.

**Comment by libormatuska** [comment]
Díky, otestuji.

Mattes

 

 

S pozdravem

Libor Matuška

________________________________________________________

Mobil +420 603 936 689 / E-mail –  <mailto:libor.mattes@gmail.com> libor.mattes@gmail.com
