### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by Afforix** [therion/therion#250]
Hello,
I'm a C++ developer, and some of my friends are using Therion for cave surveying, so I would like to offer my help with its development. I'm not familiar with the terminology and most of the features, so I don't think I will start expanding Therion soon. But I think it will be beneficial to update the code to use today's best practices to make the development easier.

I can help with:
* C++ best practices - Language features, standard library, my goal is to have simpler and safer code.
* CMake - It is de facto standard cross-platform tool for build management of C++ projects. It is good in managing include paths, compile options, finding dependencies, there is CPack for generating packages, many IDEs support CMake projects... I think that Therion is too large to have just a Makefile.
* finding bugs - I have already found and fixed a few bugs by using static code analysis and runtime error detectors (sanitizers).

I see that Therion could also use a new GUI, but that idea needs a discussion about what it should do and how to make that in the easiest way, with technologies which are currently available. In the meantime I would like to simplify development and maintenance of Therion, so it can exist for a few more decades.

Feel free to discuss what changes you think should be done, and please let me know here or via email.

**Comment by mbudaj** [comment]
Hi,

all three suggestions are excellent and the improvements are most welcome.

I suggest a call to discuss them; I'll send you an email with
further details.

Martin
