### ISSUE TITLE
The version of shapelib (libshp) in therion seems to be from 2003

### ISSUE THREAD

**Issue by wookey** [therion/therion#253]
extern/shpopen.c dbfopen.c and shapefil.h seem to be very old versions from around 2003, which generate quite a lot of warnings with a modern complier. Upstream is still being updated to at least 2018. The debian version of therion 5.5.0 is build against libshp2 v1.5 from early 2019. https://tracker.debian.org/pkg/shapelib That builds and appears to run fine (generates working shapefiles). These files should probably be updated.

Machinery in the Makefile so that we had to do less patching to build against the system version of the library would be good. But that's a separate issue I guess.

**Comment by mbudaj** [comment]
Updated in the 'devel' branch.
