### ISSUE TITLE
Therion cannot have exactly 2 fixes for a station when using Survex loop closure

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#270]
survey errorfix
	centreline
		fix st1 1 2 3 1 2 3
		fix st1 2 3 4 2 3 4
		st1 st2 5 0 0
	endcentreline
endsurvey

When using Survex loop closure, Therion fails to work, it gets stuck on "processing survey data", and then errors out without any feedback. When enabling "-d", it works correctly, so it is hard to see what the problem is. After multiple tries, I saw it say "temporary station with that name already exists", but that disappeared before I could get a screenshot, and it would not say it when trying again.

Tested with different "cs" options, it always fails.

Tested with Therion 5.5.1, Survex 1.2.42. This issue does not affect Survex itself, a .svx file can use 2 fixes for a station without problems.

**Comment by smudrak** [comment]
Hi Tarquin,

could you please check latest release? I was not successful to reproduce this bug, but it should now export multiple fixes to survex correctly.

S.

**Comment by tarquinwj** [comment]
Verifying fix. Works as expected in "Therion 5.5.1+a8c5937" after commit 4683494, on Windows 10, with Survex 1.2.42, and Survex loop closure enabled.

👍

**Comment by tarquinwj** [comment]
PS. always stressful removing so much code. "I know I must have put this here for a reason... hope I don't need it."

**Comment by smudrak** [comment]
Exactly!
