### ISSUE TITLE
Bug: Compiling large dataset yields "error -- Invalid utf-8 string"

### ISSUE THREAD

**Issue by hbeni** [therion/therion#278]
(From the mailing list)

I think commit 1c1fcf14e introduced a bug where compiling my dataset results in the error output `./therion: error -- Invalid utf-8 string!` in about 70%+ of repeated tries.
After some testing i think this is caused by corrupted memory somewhere. 

The error is dropped from here:
https://github.com/therion/therion/blob/468349490677947f4402f5b243449aeaec839881/thtexfonts.cxx#L247-L248
The cause is however, that the parameter `std::string s` contains already garbled data, probably because the initial object was already overwritten with other content.

A `git bisect` resulted in 
```
1c1fcf14e4eaf6e0bb89da513702ad9b89204ed8 is the first bad commit
commit 1c1fcf14e4eaf6e0bb89da513702ad9b89204ed8
Author: mbudaj <m.budaj@gmail.com>
Date:   Wed Aug 19 07:25:53 2020 +0200

    dynamically load EPSG/ESRI labels in Proj>=6
```
1c1fcf14e4eaf6 and later fails like described here; the ancestors c7d41d9 compile successfully all the time (tried 10 times, all successfull).

**Comment by hbeni** [comment]
(Just a side note; dropping line 247 made the compile run trough without issues and yielding the expected results)

**Comment by hbeni** [comment]
I think i found at least a hint:
https://github.com/therion/therion/blob/1c1fcf14e4eaf6e0bb89da513702ad9b89204ed8/thproj.cxx#L472-L474

When i replace line 474 with `return "";`, the unit tests will fail, but my dataset compiles 10 of 10 times again.

**Comment by Afforix** [comment]
Problem is on this line: https://github.com/therion/therion/blob/1c1fcf14e4eaf6e0bb89da513702ad9b89204ed8/thcs.cxx#L131
`rv.prjname` is now a pointer to a temporary.

**Comment by hbeni** [comment]
Indeed,
a (possible) fix is switching the two occurences with 
`thcs_get_label(params).copy(prjname, 20, 0);`

I made a PR for that (compiles 10/10 here): 
https://github.com/therion/therion/pull/280



Am 2020-10-14 23:47, schrieb Matěj Plch:
