### ISSUE TITLE
Loch and surface splays

### ISSUE THREAD

**Issue by matteopic** [therion/therion#297]
In my project I tooke some splays outside two caves to measure their relative position and the river width. All the splays taken outside the caves have been marked with "flags surface".

What I'm expecting is to not have those splay rendered in the model because they are actually not part of the cave.

![Untitled](https://user-images.githubusercontent.com/6689726/98841944-1b0d4880-2449-11eb-8aae-75813194bb14.jpg)

I think this can be done in three ways:
1) The export simply ingore surface splays
2) The export can have some new flag to let the user if export them or not
3) The export continues to include them but Loch can have an option/button to hide/show those splays 

The sources of my whole project is availabe here: https://github.com/matteopic/buco-del-bagno/

**Comment by smudrak** [comment]
Hi, those walls are from artificial scraps - sterna-plan, riva-plan. 

Normally scrap -walls off options should help - but it was not working. I have fixed this bug, so if you add -walls off option to these scraps, they will be no more present in 3d model.

Thanks for finding it.
