### ISSUE TITLE
segfault while generating continuation list from scrap without stations, can corrupt data

### ISSUE THREAD

**Issue by jonnyprouty** [therion/therion#333]
therion 5.5.6+82b4a8b

NOTE: This segfault can lead to data corruption!

Steps to reproduce:
1. Create a plan scrap using a proper XVI as a background image.
2.  DO NOT ENTER ANY STATIONS IN THE SCRAP.
3. Trace the scrap as usual (still not entering any stations).
4. Enter a few continuation points, add -text descriptions if you want, it appears to not matter.

At this point you should be able to export a PDF map which includes the new, stationless scrap, although it might act a little weird, for example coloring by altitudes wont work. 

If you try to export a list of continuations at this point, therion will segfault.

Creating a scrap with no stations isn't something I normally do (I simply forgot to enter them), but something to note! **The segfault occasionally corrupted the .th2 file with the stationless scrap!** There was text added before the "encoding utf-8" line at the beginning of the .th2 file, which appeared to be a macro name so it appears that something was overflowing and corrupting data. This didn't happen every time, but it did happen once or twice while I was trying to figure out what was going on. This was before I realized I hadn't entered any stations in the scrap.

Putting a continuation in a cross-section does NOT appear to bring about the same segfault.

I can provide an example if need be, but I imagine the behavior can be reproduced by taking any scrap that was traced over an XVI and removing the stations, and then adding a continuation point.

**Comment by smudrak** [comment]
Thanks for finding it out. I hope, it is fixed now. Could you please check and reopen if still the issue. For me it works.

**Comment by jonnyprouty** [comment]
> Thanks for finding it out. I hope, it is fixed now. Could you please check and reopen if still the issue. For me this bugfix seems to work.

I just tested it, it looks like you fixed it. Thanks for taking care of that so quickly!
