### ISSUE TITLE
format not supported -- bbox

### ISSUE THREAD

**Issue by jonnyprouty** [therion/therion#335]
In a thconfig file the following leads to an error:

```
export map -fmt bbox -output map.bbox

```
therion: error -- maps.thconfig [7] -- format not supported -- bbox

However,  the following works just fine, and generates a bbox file, as expected:

```
export map -output map.bbox
```

I should note that the project I am using does have a fixed station with a coordinate system.

**Comment by smudrak** [comment]
Should be OK now. Thanks.
