### ISSUE TITLE
Therion 5.5.7, PDF won't generate

### ISSUE THREAD

**Issue by waynesheldon** [therion/therion#339]
I got a new laptop last week, and installed the current version. I am working on my model, tried to generate my therion cave survey model. It still works perfectly in generating 3D's, Lox, KML but it won't generate a PDF.  I have used version 5.5.3 as well but get the same issue. On my old computer, it still works fine so it must be something to do with my new laptop.
Laptop is windows 10, 64 bit.

The log file is attached.
[therion.log](https://github.com/therion/therion/files/6058088/therion.log)

Any ideas?

**Comment by mbudaj** [comment]
Please run Therion with a `-d` option and attach also the following files from thTMPDIR: makempx.log, mpxerr.log and mpxerr.tex.

**Comment by waynesheldon** [comment]
Hi, thank you for response. I am not a programmer and only use the software to undertake cave surveys,  so the above doesn't make much sense to me. I can't seem to find the files you mention, Once i do find them, where do attach them? How do I run it with a -d option? Sorry about this.

**Comment by mbudaj** [comment]
Hi, there is a box 'Command line options' at the right-hand side of the XTherion user interface (use F3 to switch to the compiler screen first). Just put `-d` there and Therion will create a directory thTMPDIR inside the project's directory. You'll find the files there; attach them to this issue please.

**Comment by waynesheldon** [comment]
Hi, i get it now. I have done what you said, the mpxerr.log doesn't appear. 

Please find the other files below.
[makempx.log](https://github.com/therion/therion/files/6071589/makempx.log)

It wouldn't let me attach the mpxerr.tex file type so i have zipped it up and attached
[mpxerr.zip](https://github.com/therion/therion/files/6071627/mpxerr.zip)

Cheers

**Comment by mbudaj** [comment]
mpxerr.log is the most important of the three files. It should have been created in your case (when metapost fails to make a label using tex) and is indeed referenced in makempx.log

**Comment by waynesheldon** [comment]
mpxerr.log is not creating in my case. I have attached a zip of the entire thTMPDIR folder.
[thTMPDIR.zip](https://github.com/therion/therion/files/6078392/thTMPDIR.zip)
I have tried it on another project folder and its not there either.
If this isn't creating, what is causing the problem?

**Comment by mbudaj** [comment]
The information in the makempx.log is not very helpful. There is an issue with running pdftex to produce the labels, but it's not clear why. The reasons may vary from a broken installation to an antivirus blocking running the program.
Maybe there could be some additional information if you run the following command in the command prompt window inside the thTMPDIR:

c:/Users/wshel/AppData/Local/Therion/bin/win32/mpost.exe -debug data.mp

**Comment by tomfoord** [comment]
Interesting... this appears to be the exact same issue I'm facing with a new Windows laptop with freshly installed Therion 5.5.7!
(I posted to the users mailing group about this earlier today.)
I've tried running with the -d option as suggested above. Like Wayne, I don't have the mpxerr.log file, however I do have the other two and will attach them in a moment.

**Comment by tomfoord** [comment]
[makempx.log](https://github.com/therion/therion/files/6273909/makempx.log)

[mpxerr.zip](https://github.com/therion/therion/files/6273907/mpxerr.zip)

**Comment by tomfoord** [comment]
I'm intrigued by the possibility that this could be linked to antivirus software. I actually switched to using a different antivirus (Kapersky) on my new laptop, so maybe that's the culprit. 
@waynesheldon, I don't suppose you did something similar?

**Comment by mbudaj** [comment]
Also in this case the log files don't help much.

Could you include the output of the metapost run in the debug mode, as in
the comment
https://github.com/therion/therion/issues/339#issuecomment-798644628?
(using an actual path to the Therion installation directory: "C:/Program
Files (x86)/Therion/bin/win32/mpost.exe" -debug data.mp)

**Comment by tomfoord** [comment]
Sure, here is the result:
![Screenshot 2021-04-07 202201](https://user-images.githubusercontent.com/52840360/113922292-0a39e680-97df-11eb-980f-9d6854cc6b18.png)

When I clicked ok on the error message, I got a second error:
![Screenshot 2021-04-07 202334](https://user-images.githubusercontent.com/52840360/113922406-29d10f00-97df-11eb-8907-0b5e486c0b17.png)

**Comment by tomfoord** [comment]
* I double checked and both error messages are exactly the same! It just throws the same error twice.

**Comment by tomfoord** [comment]
Ah, but after clicking ok on the second error message, I get some more info in Command Prompt:

![image](https://user-images.githubusercontent.com/52840360/113923049-fe025900-97df-11eb-83e3-fdc87893974c.png)

**Comment by mbudaj** [comment]
Could you check the recent dev snapshot (https://therion.speleo.sk/downloads/therion-setup-dev.exe)? It should include the missing dll now.

**Comment by tomfoord** [comment]
That has fixed it! My projects are now compiling as expected. 
Thank you! :-)

**Comment by waynesheldon** [comment]
That has fixed mine as well. Thanks all for sorting this out.
