### ISSUE TITLE
Expanding Error Msg: scrap outline intersects itself in scrap

### ISSUE THREAD

**Issue by speleo** [therion/therion#346]
I frequently see the "scrap outline intersects itself" infomational error message when compiling and although it identifies the offending scrap it would help if it identified the offending line too.

The error is generated from mpost/therion.mp line 698 which simply states

      thwarning("scrap outline intersects itself");

in comparision if there is a problem with an area it provides more infomation.  Line 763

      message("[Error: area borders "& area_border[i] &" and "&
         area_border[i_] &" don't intersect in scrap " & current_scrap &
         " (file " & current_src & ")]");

Which gives a msg like this in the log file

     [Error: area borders l121-6144-3800 and l120-6188-4008 don't intersect in scrap C1SP1@C1 (file C1.th2 [1250])]

Would it be possible to provide more debug info for "scrap outline intersects itself" errors?

**Comment by mbudaj** [comment]
The scrap reference is produced by thwarning() automatically, so it should be included in the output.

I'm afraid it's not possible to include the exact reference to the source line, as the scrap outline can be defined using multiple disconnected paths located in different parts of the file. The reference to the file could be added, but usually you can easily infer the file name from the scrap name.

**Comment by speleo** [comment]
my understanding is that thwarning is defined in the same file (line 783) as:

def thwarning (expr m) =
  message("[Warning: " & m & " in scrap " & current_scrap & "]");
enddef;

So if we were to use a syntax like 

  message("[Error: Scrap Outine "& outline[i] &" intersects itself in scrap " & current_scrap &
     " (file " & current_src & ")]");

then it could give a pointer to the specific border which is throwing the warning.  Maybe this would be better:

   thwarning("Scrap Outine "& outline[i] &" intersects itself");

Assuming this would work then **outline[i]** would need to be replaced with the correct variable.

**Comment by mbudaj** [comment]
Unfortunately this wouldn't work. MetaPost can't detect which part of the line intersects itself at all. 

This message actually means that MetaPost can't determine whether the cyclic line (in this case scrap outline) is drawn clockwise or counter-clockwise (which usually means there is a figure-8-like loop somewhere).

Maybe such detection could be implemented in the (not so near) future using some numerical method.

**Comment by speleo** [comment]
Thanks for the explaination, that makes sense.  These warnings don't actually affect the final output but I'm always concious of trying to compile warning free.  

I'll close the issue.
