### ISSUE TITLE
OSX Panels text disappear

### ISSUE THREAD

**Issue by fratnike** [therion/therion#355]
Dear all,

could you please check why the "section text" on the side panels appear only when you click the mouse? (see attached mp4)

I have tried the "bwidget demo file" and all works fine.
![Screenshot 2021-04-12 at 09 32 37](https://user-images.githubusercontent.com/6651334/114357480-107aea80-9b72-11eb-805f-fc3460efe2dd.jpg)

Thank you in advance
enrico 

https://user-images.githubusercontent.com/6651334/114357099-9fd3ce00-9b71-11eb-935e-4dfb5196fb75.mp4

**Comment by smudrak** [comment]
Hi Enrico, for some unknown reason - max ignores button background setting but accepts foreground. Then button is white foreground/white background text.

In 12aa6f5 I have extracted these colors to settings variables and changed default colors for Mac OS X. You may try.

And if you create .therion/xtherion.ini file in your home directory with
```
set xth(gui,ctrlBtnFg) black
set xth(gui,ctrlBtnBg) white
set xth(gui,ctrlBtnActiveFg) black
set xth(gui,ctrlBtnActiveBg) lightGray
```
you can experiment with these colors. If you will find better ones, I can set them as Mac OS X default.

HTH, S.

**Comment by fratnike** [comment]
Thank you Stacho,

    it works fine and now the button label are visible!
The color are not really important, personally I prefer a dark blue like #0000ae instead of black but really it is not important.

enrico
![Screenshot 2021-04-15 at 10 09 50](https://user-images.githubusercontent.com/6651334/114836615-24715700-9dd3-11eb-912c-6723f3dacaab.jpg)

**Comment by smudrak** [comment]
Thx for feedback, color changed to darkBlue, closing issue.
