### ISSUE TITLE
Therion parses `color` metapost command in metapost-code block

### ISSUE THREAD

**Issue by hbeni** [therion/therion#356]
I want to store the used background color in a metapost variable so i can adjust in the global layout:

```
code metapost
    color col_water_tmp_bg;
    col_water_bg :=(0.60, 0.60, 0.95);     % Wasserflächen
    col_water_tmp_bg :=(0.60, 0.60, 0.95); % Temporäre Wasserflächen
    trans_water_tmp_bg := 0.85;            % Transparenzgrad temp. Wasserflächen
endcode
```

However, therion tries to parse the "color" command inside the metapost block, not allowing me to use that metapost datatype:
`./therion: error -- /tmp/test/layout/hvho.layout.thc [191] -- /tmp/test/layout/hvho.layout.thc [191] -- not enough option arguments -- color -- must be 2`

I sugest, that the parser does not try to parse metapost-stuff between `code metapost`/`endcode` tags in layout definitions.

**Comment by smudrak** [comment]
Hmm, it would be possible to ignore all commands between code/endcode, but it would be backwards incompatible change.

It is enough tu start your "color col_water_tmp_bg;" line with ! and it will force therion to interpret this line as a line with data, not an option.

```
code metapost
!    color col_water_tmp_bg;
    col_water_bg :=(0.60, 0.60, 0.95);     % Wasserflächen
    col_water_tmp_bg :=(0.60, 0.60, 0.95); % Temporäre Wasserflächen
    trans_water_tmp_bg := 0.85;            % Transparenzgrad temp. Wasserflächen
endcode
```
... should do the trick.

**Comment by hbeni** [comment]
> It is enough tu start your "color col_water_tmp_bg;" line with ! and it will force therion to interpret this line as a line with data, not an option.

Thank you, yes this is enough!
I added a pull request for adding this knowledge to the thbook.
