### ISSUE TITLE
Export 3d models

### ISSUE THREAD

**Issue by kotfantazer** [therion/therion#359]
Hi! I need help. Can I export 3d model with stations with labels?
It's all the same if I turn on the setting: Scene -> Settings -> Stations -> All and turn on "Labels/Name" checkbox.

**Comment by smudrak** [comment]
This is strange, stations are all the time exported with labels.
If you check that all stations should be marked and labels, labels are shown next to station.
See attached image.
![image](https://user-images.githubusercontent.com/10210555/116129272-348a1000-a6ca-11eb-9e0f-f9ba03dfa660.png)

**Comment by kotfantazer** [comment]
Hi! I'm exporting to format *.vtk from Loch app (File->Export). Then I'm looking at exported file in the program ParaView and do not see stations.

**Comment by smudrak** [comment]
I am afraid, export of centerline & surface to VTK is not implemented. Only passage walls are exported.
