### ISSUE TITLE
Area bedrock doesn't superimpose line border

### ISSUE THREAD

**Issue by martinsluka** [therion/therion#362]
As you may see in two attached pictures, I created a simple area bedrock defined by line border. This area is overlapping another line border. But in exported PDF the bottom line border is still visible, what is not correct I suppose.

![otisk_ 2021-04-25 v 16 25 23](https://user-images.githubusercontent.com/7187070/115997515-9face700-a5e3-11eb-9083-4b83ce8a4a7f.png)
![otisk_ 2021-04-25 v 16 26 45](https://user-images.githubusercontent.com/7187070/115997521-a4719b00-a5e3-11eb-8802-4e30d8f49bb7.png)

**Comment by smudrak** [comment]
Is the area bedrock in .th2 file above or below area water? Symbols above should overlap symbols below.

**Comment by martinsluka** [comment]
Checked.
