### ISSUE TITLE
Transparent area ?

### ISSUE THREAD

**Issue by robertxa** [therion/therion#364]
Hi,

In my Therion projects, I have defined a some years ago a new transparent area, following the wiki (Transparent Area on https://therion.speleo.sk/wiki/metapost?s[]=transparent):
`def_transparent_rgb(tr_lchamois, 0.82, 0.75, 0.48);

def a_u_galerie(expr P) =
	T:=identity;
	thfill P withtransparentcolor tr_lchamois;
enddef;`

Until recently, it was working OK, but since the Therion version of ~03/04/2021 until today (), compiling is raising this error:

This is MetaPost, version 1.999 (TeX Live 2015) (kpathsea version 6.2.1)  27 APR 2021 19:22
**data.mp
(/usr/local/texlive/2015/texmf-dist/metapost/base/mpost.mp
(/usr/local/texlive/2015/texmf-dist/metapost/base/plain.mp
Preloading the plain mem file, version 1.005) ) (./data.mp
{randomseed:=42}
 [4001] [4002] [4003] [4004] [4005] [4006] [4007] [4008] [4009] [4010] [4011] [
4012] [4013] [4014]
[4015]
>> def_transparent_rgb
! Isolated expression.
<to be read again> 
                   (
l.7396 def_transparent_rgb(
                           tr_lchamois, 0.82, 0.75, 0.48);
I couldn't find an `=' or `:=' after the
expression that is shown above this error message,
so I guess I'll just ignore it and carry on.

! Extra tokens will be flushed.
<to be read again> 
                   (
l.7396 def_transparent_rgb(
                           tr_lchamois, 0.82, 0.75, 0.48);
I've just read as much of that statement as I could fathom,
so a semicolon should have been next. It's very puzzling...
but I'll try to get myself back together, by ignoring
everything up to the next `;'. Please insert a semicolon
now in front of anything that you don't want me to delete.
(See Chapter 27 of The METAFONTbook for an example.)

! Extra tokens will be flushed.
<to be read again> 
                   withtransparentcolor
a_u_galerie->...;thfill(EXPR0)withtransparentcolor
                                                  .tr_lchamois;
l.7443 )))
          ;
I've just read as much of that statement as I could fathom,
so a semicolon should have been next. It's very puzzling...
but I'll try to get myself back together, by ignoring
everything up to the next `;'. Please insert a semicolon
now in front of anything that you don't want me to delete.
(See Chapter 27 of The METAFONTbook for an example.)

[1] [2] [3] [4] (./mptextmp.mp) [5] (./mptextmp.mp) (./mptextmp.mp)
(./mptextmp.mp) (./mptextmp.mp) (./mptextmp.mp) (./mptextmp.mp) [6] )
 
Here is how much of MetaPost's memory you used:
 1770 strings using 45833 characters
 3574680 bytes of node memory
 1721 symbolic tokens
 9i,81n,16p,312b,5f stack positions out of 16i,96n,20p,312b,6f
21 output files written: data.1 .. data.4015

#################### end of metapost log file ####################
therion: error -- metapost exit code -- 512
writing xtherion file ... done

Is it a bug induced by one of the recent updates?

If you need more info, let me know,
Cheers,
Xavier

**Comment by mbudaj** [comment]
This is an incompatible change planned for the next release. Transparent colors handling is much improved (no need to define them in advance + the actual value of the opacity can be specified).

See https://github.com/therion/therion/blob/devel/CHANGES for more details. Note, that there is some naming difference between devel and master; the plan is to use devel's 'withalpha'.

**Comment by robertxa** [comment]
Thanks Martin !

OK, I needed some times to find the right command, but now it works:
- with the devel version, this is withalpha (I guess)
- with the Master version (that I am using), this is withtransparency.

That is true that it simplify the way to handle transparency. Great job !

Xavier
