### ISSUE TITLE
Ceiling-step line doesn't react on order of commands

### ISSUE THREAD

**Issue by martinsluka** [therion/therion#368]
I drawn two ceiling-step lines. They were not full exported because they were overlaped by other objects - rock-borders. I changed their position just after header of scrap, but they are exported in the same way. xtherion restarted, th2 file closed and reloaded. The same results.

![Snímek obrazovky 2021-05-05 v 20 19 18](https://user-images.githubusercontent.com/7187070/117190529-d652e080-addf-11eb-9959-ac008ae5c0f5.png)
![Snímek obrazovky 2021-05-05 v 20 15 48](https://user-images.githubusercontent.com/7187070/117190538-d9e66780-addf-11eb-821a-2aed4097c2a5.png)

**Comment by martinsluka** [comment]
Rock-border overlapped the ceiling-step in any case.

**Comment by martinsluka** [comment]
The same with chimney

**Comment by smudrak** [comment]
Could you please post your .th2 file here - you have probably clip off set for the rock borders.

**Comment by martinsluka** [comment]
You are right. But anyway, ceiling-step and chimney are allways over any block.

**Comment by CaverBruce** [comment]
From the Therion Book: clip <on/off>  specify whether a symbol is clipped by the scrap border. 

A rock border is not a scrap border, so the clip status of objects should not affect rendering of objects above or below them.  Should only affect whether scrap border clips them. So surely this remains a bug? (although have not tested it myself)

**Comment by martinsluka** [comment]
Ceiling-step and chimney lines are in any case above of any object of a passage. 

It looks as a bug. 

Martin

Odesláno z iPhonu

5. 5. 2021 v 22:17, Bruce ***@***.***>:
