### ISSUE TITLE
"plaquette" option for "sketch-warp" command doesn't work

### ISSUE THREAD

**Issue by martinsluka** [therion/therion#376]
Therion book:
‘sketch-warp’
Syntax:
• sketch-warp <algorithm>
Specifies which scrap warping (morphing) algorithm to use. Possible algorithms are
line—the default; plaquette—invented by Marco Corvi.

thconfig:
layout morf
  sketches on
  sketch-warp plaquette
 endlayout 

compilation:
therion: error -- colibri_41.thconfig [7] -- colibri_41.thconfig [7] -- unknown option -- sketch-warp plaquette

**Comment by smudrak** [comment]
For me, it seems to work. See attached example.
[plaq.zip](https://github.com/therion/therion/files/6548601/plaq.zip)

**Comment by martinsluka** [comment]
For me not. See attached example. xvi file is generated evidently with centerline and with an image, but sketch is not visible. Without option sketch-warp plaquette it is visible.
![Snímek obrazovky 2021-05-27 v 12 05 32](https://user-images.githubusercontent.com/7187070/119808914-ddec3d80-bee4-11eb-828d-5444d07c1433.png)
![Snímek obrazovky 2021-05-27 v 12 05 15](https://user-images.githubusercontent.com/7187070/119808921-df1d6a80-bee4-11eb-885e-d5456926aeb8.png)

[Archiv.zip](https://github.com/therion/therion/files/6553098/Archiv.zip)
