### ISSUE TITLE
Install therion 6.0.0 on Debian?

### ISSUE THREAD

**Issue by BenoitURRUTY** [therion/therion#379]
Hi,
I would like to install the last version of therion on my debian. The debian repository have the 5.4 which is old. 
How can I install the last version? And how to compile it?
Thanks 
Benoit

**Comment by mbudaj** [comment]
There are instructions in the Appendix to the [thbook](https://github.com/therion/therion/releases/download/v6.0.0/thbook-v6.0.0.pdf), pp. 78–79. See also sections 'install' and 'run' [here](https://github.com/therion/therion/blob/master/.github/workflows/cmake.yml) as an example.
