### ISSUE TITLE
xvi import problem

### ISSUE THREAD

**Issue by matls** [therion/therion#386]
[therionproblemxvi.log](https://github.com/therion/therion/files/7230411/therionproblemxvi.log)
I have a problem with Pockettopo import in to TH2 file in version 6.0.2 (see in log file). In version 6.0.1 it's work OK.

**Comment by CaverBruce** [comment]
I suspect that has been fixed on 17 September in https://github.com/therion/therion/commit/23b301ec0a9262c09c4bd2e70138a0eb57a6e447

You could try that or any of the more recent updates.

**Comment by matls** [comment]
Sorry, I missed that
