### ISSUE TITLE
sketch import file browser case-sensitive to filename extensions

### ISSUE THREAD

**Issue by echarlie** [therion/therion#390]
when attempting to import a background image in xtherion 5.5.7 on debian, the browser ignores non-lowercase file extensions. e.g. filename.JPG will not appear in the dialogue (however .jpg will). It appears that `tk_getOpenFile` called here (?) https://github.com/therion/therion/blob/21da146108213db5baab87b9b3910be743205dd4/xtherion/mapcal.tcl#L33 is case-sensistive.

**Comment by smudrak** [comment]
Thanks for finding out, the same problem with my ubuntu 20.04. Should be fixed in the latest commit.
