### ISSUE TITLE
Infinite Loop "unable to determine direction on zero-length path in scrap"

### ISSUE THREAD

**Issue by BdHr** [therion/therion#395]
Hi,

I have detect this bug, existing for a long time (some test on older version have the same effect). 

If a line is only made of one point, therion is freezed in a infinite loop.
therion.log alert with this message  "unable to determine direction on zero-length path in scrap".
The only way to stop is to kill the software :-(

Example in a th2 file , in a scrap :

`
line pit -close off
  2299.75 -872.5
endline
`

Cheers,
Bertrand Hauser
France

**Comment by smudrak** [comment]
Thanks for pointing out, it should be fixed now.
