### ISSUE TITLE
import SVG file issue 

### ISSUE THREAD

**Issue by gemist** [therion/therion#396]
I did my first cave survey using TopoDroid. However I am not satisfied with Topodroid (therion) export, so I would like to draw walls and other cave features on my own inside xtherion (importing svg file including grid produced by Topodroid). 

procedure to reproduce error: 
1) open xtherion
2)  Window -> Map Editor (F2)
3) File -> New
4) File -> Save -> save as test.th2
5) File -> Import -> test.svg
6) during import I am getting next error message (test.log).
[test.log](https://github.com/therion/therion/files/7801364/test.log)

I am attaching svg file (just rename test.txt into test.svg; it seems github does not support svg files).
[test.txt](https://github.com/therion/therion/files/7801382/test.txt)

On the other hand, it does not work for me, even if I try to export svg file using therion and importing it again using above procedure. What am I doing wrong? Do you suggest any workaround? 

I am using xtherion 6.0.4 on arch linux.

**Comment by gemist** [comment]
At the end I discovered I need to export only th and th2 (above view and side view) files from TopoDroid to create cave maps. So svg import is not needed. However svg import still does not work.

**Comment by smudrak** [comment]
Thanks for finding this issue.

Unfortunately, xtherion does not support import of a complex SVG files - like are those generated by therion. This feature was intended to be used for simple SVG files generated from drawing programs like Illustrator or Inkscape. But honestly, I did not know this feature exists in xtherion.

Anyway, I have tried to remove the error and fix some SVG import issues in latest commit. But still, SVG files generated by therion can not be used directly in xtherion. You need to convert them to some bitmap (PNG?) and use these as a background image for drawing maps.

To create maps in xtherion based on TopoDroid drawings, we are using TopoDroid export to XVI. This is xtherion internal vector image format with some additional metadata (like station names) that is supposed to be used as a background image. Or you may still convert SVG to bitmap and use bitmap as a background.
