### ISSUE TITLE
Loch not working properly on HiDPI screen

### ISSUE THREAD

**Issue by ladislavb** [therion/therion#399]
Loch is not working properly on Retina (and maybe other HiDPI screens as well). Screenshots from my machine clearly showing the problem attached - same window, same model, just moved between built-in Retina screen (1st screenshot) and external Full HD display (2nd screenshot). The view scene is much smaller (something like 1/4 of the window size) on the Retina screen and cannot be resized.

HW: MacBook Pro 14" (Apple Silicon if important), Built-in display resolution: 3024x1964 px.
OS: macOS 12.1 Monterey
Therion/Loch version: 6.0.4+f8a57f4

<img width="1180" alt="loch_retina" src="https://user-images.githubusercontent.com/9359253/152771583-894a5a1c-bb62-4cd3-af0e-0cc2effe6906.png">

![loch_external_fullhd](https://user-images.githubusercontent.com/9359253/152773160-f15f5e15-09eb-407c-bd0d-83ef9c56e5f9.png)

**Comment by smudrak** [comment]
It should be fixed in acbf071.

**Comment by ladislavb** [comment]
Thank you, works. Legend could still be a tad bigger - see screenshot. Anyway, Homebrew formula (https://github.com/ladislavb/homebrew-therion) has been updated as the main problem is fixed now.
<img width="1512" alt="Snímek obrazovky 2022-03-08 v 0 18 23" src="https://user-images.githubusercontent.com/9359253/157134612-eb6e9a85-72de-4269-83e6-a06ad74a68c3.png">

**Comment by ladislavb** [comment]
Fixed in Therion 6.0.6.
