### ISSUE TITLE
Drag handle on rope causes an error

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#423]
Rendering an extended elevation (or projected elevation) using the default rope symbol.
Rope is very basic, with three points, the middle of which has a drag handle on one side (normally this uses my own rope symbol code, where drag handles make sense).
Direction of the drag handle is not important.

Throws a load of error messages in the output, and fails to compile.

```
survey brokenextend
  scrap whocares -projection extended -scale [80.0 769.0 276.75 965.75 0.0 0.0 10 10 m]
    line rope -clip off
      339.9 931.0
      339.9 866.5
      357.25 840.25 329.0 804.5 329.0 804.5
      smooth off
    endline
    point 344.767 733.264 station -name 1
  endscrap
  centreline
    date 2022.01.01
    extend start 1
    data normal from to length compass clino
    1 2 10 0 -90
  endcentreline
endsurvey
```

Compiled with:
```
source "brokenextend.th"
export map -proj extended -o "extenddebug.pdf"
```

**Comment by mbudaj** [comment]
Thanks for reporting. The real issue was that the first two points have the same x-coordinate. Should be fixed in 2865626.
