### ISSUE TITLE
Copy commands run in the wrong order

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#425]
Commands/options in a layout are run in sequence, so that the last one has priority.
However, copy commands are run in reverse order, as well as being out of sequence with other commands.

```
layout first
  symbol-hide point stalactite
  symbol-hide point water-flow
  symbol-hide point dig
endlayout
layout second
  symbol-show point stalactite
endlayout
layout third
  symbol-show point water-flow #overrides the copy below
  copy first #first one wins with copy
  copy second
  symbol-show point dig #overrides the copy above
  symbol-hide point anchor
  symbol-show point anchor #second one wins normally
endlayout
source "copy.th"
select copyMP@copy
export map -proj plan -layout third -o "copy.pdf"
```

In my mind, the most obvious way to handle this is to have everything applied in the order it gets specified and copied, so stalactites, digs and anchors are all visible, and water-flow is hidden.

However, Therion 6.1.0 (Windows 10) seems to run all copy commands first (maybe intentional? but if so it needs to be explicitly stated in the Therion book). And it runs them in the opposite order from how they were specified. As a result, digs and anchors are visible (both as expected), water-flow is visible (possibly intentional?) and stalactites are hidden (unpredictable/bad).

**Comment by speleo3** [comment]
I was about to report the same issue, with some additional observations.

```
layout l_base
  scale 1 100
  symbol-set AUT
  symbol-hide point stalagmite
endlayout

layout l_overlay
  scale 1 200
  symbol-hide line rock-border
  symbol-hide point stalactite
  symbol-show point stalagmite  # show
  symbol-hide group sections
endlayout

layout l_combined
  copy l_base
  copy l_overlay
endlayout

layout l_combined_reversed
  copy l_overlay
  copy l_base
endlayout

# scale from l_overlay
# symbol visibility as in l_base (only stalagmite hidden)
# section scrap hidden (as in l_overlay)
export map -o combined.pdf -layout l_combined

# scale from l_base
# symbol visibility as in l_overlay (only stalagmite visible)
# section scrap hidden (as in l_overlay)
export map -o combined_reversed.pdf -layout l_combined_reversed
```

* Some commands are run in order, like `scale`
* `symbol-set` resets previous `symbol-hide` commands
* `symbol-hide group sections` might get applied partially (scrap hidden, line shown)
