### ISSUE TITLE
Loch shows an error on Windows

### ISSUE THREAD

**Issue by tarquinwj** [therion/therion#426]
Therion 6.1.0 standard (msys2) Windows installer on the Therion download page.
When running Loch on Windows 10, it says:

---------------------------
Fatal Error
---------------------------
Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1016,wx
containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1017,wx
containers,compatible with 2.8).
---------------------------
OK
---------------------------

This error prevents Loch from running. The MXE installer does not show this problem.

**Comment by mbudaj** [comment]
Should be fixed in the recent commits (the installers are in the Actions section). If you still encounter this problem, please reopen the issue.
