### ISSUE TITLE
wxWidgets 3.2 support

### ISSUE THREAD

**Issue by ojwb** [therion/therion#447]
Building with wxWidgets 3.2.0 completes, but running `loch` pops up a dialog warning:

```
./src/common/sizer.cpp(2258): assert "CheckSizerFlags(!((flags) & (wxALIGN_CENTRE_VERTICAL)))" failed in DoInsert(): wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: only horizontal alignment flags can be used in vertical sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.
```

If I click "Continue" I get several further similar warnings.

Running `WXSUPPRESS_SIZER_FLAGS_CHECK= loch` seems to give a working loch from a quick play.

It would be good to address this as we're aiming to eliminate wxwidgets3.0 before the next Debian release.

**Comment by Afforix** [comment]
Hi, most of these warnings should already be fixed in https://github.com/therion/therion/pull/439. Can you please provide steps to reproduce this issue?

**Comment by ojwb** [comment]
Jjust running literally `loch` when using a build compiled with wxWidgets 3.2.0 is enough to trigger this.

I was testing recompiling the therion package from Debian unstable which looks like it doesn't include that patch.  I'll try applying it.

**Comment by ojwb** [comment]
Great, that seems to have fixed all the assertions.
