### ISSUE TITLE
Grid missing in atlas mode

### ISSUE THREAD

**Issue by Bergil06** [therion/therion#454]
In atlas mode, the layout command

  grid-size 100 100 100 m

do not work. No grid line (on extended survey) or no cross positions (on map survey) are drawn on the final map.
We have the problem in plan (no cross) and in extended view (no lines)
Can we still have the grid in atlas mode ?
Thanks

**Comment by CaverBruce** [comment]
Grids for exported pdf atlas should be working the same as for exported pdf maps.  I have recent examples where atlas have grids in both plan and in elevation.
Make sure you have set:
grid <off/top/bottom>

**Comment by Bergil06** [comment]
Your write, the "grid bottom" option was missing.
With the option this work find.
You can close the issue.
Thanks
