### ISSUE TITLE
JPG On Mac

### ISSUE THREAD

**Issue by kmichael500** [therion/therion#478]
Jpgs do not work on xtherion on Mac.

**Comment by martinsluka** [comment]
It works for me:
![otisk_ 2022-12-30 v 18 59 03](https://user-images.githubusercontent.com/7187070/210099533-60efe094-54d3-43a6-a027-f2c84327fb67.png)

**Comment by kmichael500** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/4175685/211162595-0c361a9f-665f-430c-a54c-be99d9028f42.png">

This is the error I am getting.

**Comment by martinsluka** [comment]
And before it was able to load it?M. Odesláno z iPhonu7. 1. 2023 v 18:16, Michael Ketzner ***@***.***>:﻿

This is the error I am getting.

**Comment by ladislavb** [comment]
Hi Michael,

based on the error message you are using progressive Jpeg file - see https://www.liquidweb.com/kb/what-is-a-progressive-jpeg/
Try to open the file in some bitmap editor (for example GIMP) and save it as standard Jpeg file and try again.

---
Ladislav Blažek
