### ISSUE TITLE
Incorrect output coordinates system

### ISSUE THREAD

**Issue by Droniste** [therion/therion#482]
We encountered an output coordinates system issue after we upgraded Therion from v.6.0.6 to v.6.1.5 (latest). The output coordinates system picked up by Therion for our cave network is now incorrect : with v.6.0.6, we get UTM31, which is definitely correct, but with v6.1.5 we now get UTM 30, which is incorrect.

**Comment by mbudaj** [comment]
Could you attach some minimal example? Thanks

**Comment by Droniste** [comment]
therion.log for the same database ran with the 2 Therion versions. 
[therion_6.0.6.log](https://github.com/therion/therion/files/10369739/therion_6.0.6.log)
[therion_6.1.5.log](https://github.com/therion/therion/files/10369740/therion_6.1.5.log)

and database sample to run in both version.
[Therion_ocs_issue_data_sample.zip](https://github.com/therion/therion/files/10369759/Therion_ocs_issue_data_sample.zip)
