### ISSUE TITLE
Can't open Therion

### ISSUE THREAD

**Issue by rohbenj** [therion/therion#499]
Hi, 

When i open Therion via the terminal i have this error : 

_therion 6.1.2 (2022-07-11)
cavern - Survex 1.4.3
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./fonttest.tex
checking optional fonts csr10 csti10 csbx10 csss10 csssi10 ... OK
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./fonttest.tex
checking optional fonts cmcyr10 cmcti10 cmcbx10 cmcss10 cmcssi10 ... OK_

> therion: error -- source files not specified

Thanks

**Comment by smudrak** [comment]
Hi, therion is just a "compiler". Please, check out the tutorials on https://therion.speleo.sk/wiki/doku.php 

S.
