### ISSUE TITLE
no usable coordinate transformation found since the recent update

### ISSUE THREAD

**Issue by begbie55** [therion/therion#502]
Hi,

since the latest update I am getting an error in my recent projects: no usable coordinate transformation found.
I reversed to 6.1.6 and the problem is gone.

My cs:  EPSG:2157

Thanks.
Kind regards
Daniel

**Comment by mbudaj** [comment]
Hi,

could you check if the latest  commit in the master branch works? There
were some fixes related to this issue.

Instructions how to download it are here:
https://therion.speleo.sk/download.php

Martin

**Comment by begbie55** [comment]
Hey,
The latest commit in the master branch works.
Thank you!
Daniel
