### ISSUE TITLE
no usable coordinate transformation found

### ISSUE THREAD

**Issue by cepelabs** [therion/therion#510]
On Therion for Windows 6.1.7 if I put in a survey coordinate in WGS84 geographic format with cs lat-long I get "no usable coordinate transformation found".
The problem seem to be related to projs (with 6.1.6 all run correctly).
A friend suggest me to add proj-auto off in therion.ini and this will solve the problem but is not a real solution.

**Comment by mbudaj** [comment]
See https://github.com/therion/therion/issues/502
