### ISSUE TITLE
trying to subscribe the mailing list 

### ISSUE THREAD

**Issue by Droniste** [therion/therion#511]
Hi there,

I've been trying subscribing the therion mailing list by sending empty email  at therion-subscribe@speleo.sk, but I carry on getting the following message : _Remote server returned message detected as spam -> 554 5.7.1 Service unavailable; Client host [40.92.58.105] blocked using zen.spamhaus.org_
Any chance to add my email to the list : th(UNDERSCORE)marguet(AT)hotmail(DOT)com
Cheers
Thomas

**Comment by smudrak** [comment]
Hi, thanks for info. This is very strange, hopefully mailing list works.
You should be subscribed now.
S.

**Comment by Droniste** [comment]
Thanks!
________________________________
De : Stacho Mudrak ***@***.***>
Envoyé : Saturday, June 24, 2023 10:46:26 PM
À : therion/therion ***@***.***>
Cc : Thomas Marguet ***@***.***>; Author ***@***.***>
Objet : Re: [therion/therion] trying to subscribe the mailing list (Issue #511)


Hi, thanks for info. This is very strange, hopefully mailing list works.
You should be subscribed now.
S.

**Comment by jmbegley** [comment]
I think that there are still some issues with the therion mailing list server. I tried to send a message asking a couple of questions question from a GMail account, and have received the following message:

Delivery incomplete
There was a temporary problem while delivering your message to therion@speleo.sk. Gmail will retry for 46 more hours. You'll be notified if the delivery fails permanently.
The response from the remote server was:  554 5.7.1 Service unavailable; Client host [209.85.166.180] blocked using zen.spamhaus.org

I know of another subscribed user who has failed to send a message to the therion mailing list, receiving the following error message:

Reporting-MTA: dns; [smtp-auth.no-ip.com]
X-Postfix-Queue-ID: 4QvJPj5DkGz7mkC
X-Postfix-Sender: rfc822; [xx@mail.account]
Arrival-Date: Sun,  2 Jul 2023 19:04:09 +0000 (UTC)
Final-Recipient: rfc822; [therion@speleo.sk]
Original-Recipient: [rfc822;therion@speleo.sk](mailto:rfc822%3Btherion@speleo.sk)
Action: failed
Status: 5.7.1
Remote-MTA: dns; [mail.speleo.sk](http://mail.speleo.sk/)
Diagnostic-Code: smtp; 554 5.7.1 Service unavailable; Client host
[8.23.224.60]
     blocked using [zen.spamhaus.org](http://zen.spamhaus.org/)

The mailing list archives are suspiciously quiet for the last few weeks - either everyone is off an expedition somewhere or there are issues with the mailing list server.

**Comment by Droniste** [comment]
Not sure I'm actually signed in the mailing list... I have received no email since this ticket was closed (maybe there were none), nor I know the email address of the list to send a message...
Back then I tried to sign up with hotmail and gmail addresses and both were eventually rejected although it took longer for my gmail address to get the rejection message.
