### ISSUE TITLE
Issues with the therion mailing list server

### ISSUE THREAD

**Issue by jmbegley** [therion/therion#515]
I think that there are still some issues with the therion mailing list server. I tried to send a message asking a couple of questions question from a GMail account, and have received the following message:

Delivery incomplete
There was a temporary problem while delivering your message to [therion@speleo.sk](mailto:therion@speleo.sk). Gmail will retry for 46 more hours. You'll be notified if the delivery fails permanently.
The response from the remote server was: 554 5.7.1 Service unavailable; Client host [209.85.166.180] blocked using zen.spamhaus.org

I know of another subscribed user who has failed to send a message to the therion mailing list, receiving the following error message:

Reporting-MTA: dns; [smtp-auth.no-ip.com]
X-Postfix-Queue-ID: 4QvJPj5DkGz7mkC
X-Postfix-Sender: rfc822; [[xx@mail.account](mailto:xx@mail.account)]
Arrival-Date: Sun, 2 Jul 2023 19:04:09 +0000 (UTC)
Final-Recipient: rfc822; [[therion@speleo.sk](mailto:therion@speleo.sk)]
Original-Recipient: [rfc822;therion@speleo.sk](mailto:rfc822%3Btherion@speleo.sk)
Action: failed
Status: 5.7.1
Remote-MTA: dns; [mail.speleo.sk](http://mail.speleo.sk/)
Diagnostic-Code: smtp; 554 5.7.1 Service unavailable; Client host
[8.23.224.60]
blocked using [zen.spamhaus.org](http://zen.spamhaus.org/)

The mailing list archives are suspiciously quiet for the last few weeks - either everyone is off an expedition somewhere or there are issues with the mailing list server.

**Comment by jmbegley** [comment]
See also https://github.com/therion/therion/issues/511

**Comment by pvernant** [comment]
Same here, I cannot anymore send emails with my gmail address (it was working fine until not so long ago). I tried to subscribe with an icloud address and got turned down to. Would be great to be back on the list !

**Comment by mbudaj** [comment]
It should be fixed now. Please write a comment here if it still doesn't
work for you.
