### ISSUE TITLE
Unexpected error with dive data

### ISSUE THREAD

**Issue by speleoluc** [therion/therion#547]
An Auriga user reports a problem when exporting his dive data to Therion 6.1.18. 

Error message: [90] -- length reading is less than change in depth

Offending data: 

units tape meters
units compass degrees
units depth meters
units backcompass degrees
units backclino degrees
calibrate tape 0.00 
calibrate compass 0.00
calibrate depth 0.00 1

data diving from to length compass  fromdepth todepth  left right up down

line 89 in TH file:

  72   73      0.30    74.5     -8.0    -8.3     0.00    0.00    0.00    0.00 

What's wrong with a -0.3m depth change for a 0.3m survey shot? Is this a rounding error? The cave is strictly linear, with sequential stations. I looked for a relevant fix in the list of changes for version 6.2.0, but it is quite vague.

Luc Le Blanc

**Comment by speleoluc** [comment]
I imported this dive data into Excel and witnessed the same rounding error : the depth change between -8.0 and -8.3 gets computed as 0,3000000000000010, thus explaining this unexpected error message.

CONCLUSION : This is a ROUNDING ERROR BUG in Therion.

FIX : Apply a proper rounding of the depth change before comparing it with the shot length. Ex. add a 1e-7 epsilon and then round to 2 or 3 decimals.

USER WORKAROUND : Cheat the survey data by adding a centimeter to vertical dive shots. Inelegant, but it works.

Luc Le Blanc

**Comment by speleoluc** [comment]
But make sure you implement rounding before comparing, otherwise, the problem will remain due to the tiny imprecision of the depth change computation.

**Comment by speleobrad** [comment]
I have not found the "rounding bug" but then again, I was solving my own problem which I thought might solve yours too. 
If you don't feel that's the case, feel free to dig into the code and find a solution.

**Comment by speleoluc** [comment]
Just put these dive data lines into your TH file and see if it pops up an alert.

data diving from to length compass fromdepth todepth left right up down
72 73 0.30 74.5 -8.0 -8.3 0.00 0.00 0.00 0.00

If so, your solution is incomplete. It's missing some truncation of the subtraction decimals.

I'm not a Therion user. I was just reporting the problem a friend had when transferring dive data from Visual Topo to Therion.

**Comment by smudrak** [comment]
Should be fixed in the latest commit. Added some tolerance to that check. Thanks!
