### ISSUE TITLE
Unexpected dependency when compiling therionbook

### ISSUE THREAD

**Issue by RadostW** [therion/therion#548]
# In `thbook`, `make all`  doesn't produce the therion book.
It asks for `version` instead

## Steps to Reproduce
1. Navigate to `thbook` dir
2. Run `make all`

## Expected Behavior
Therion book is compiled.
`thbook.pdf` is created

## Actual Behavior

Following output is printed to stdout

```
make all
pdftex thbook.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./thbook.tex
(/usr/share/texlive/texmf-dist/tex/generic/pdftex/glyphtounicode.tex)
(./etc/supp-mis.tex
loading : Context Support Macros / Miscellaneous (2004.10.26)
) (./etc/supp-pdf.tex
loading : Context Support Macros / PDF
)
\thversion=
```

Providing `\thversion` interactively and creating `version.tex` with contents `1.0` allows user to proceed

## Proposed Solution(s)
One of the following
a) Include `version.tex` into the repository with some valid value of version
b) Add creation of `version.tex` into `make all`
c) Add README to the `thbook` directory describing the process

**Comment by Afforix** [comment]
Recommended workflow is to use CMake. If you want to build just the `thbook`, you can do:
```bash
mkdir build
cd build
cmake -DBUILD_LOCH=OFF -DBUILD_THERION=OFF -DBUILD_XTHERION=OFF -DBUILD_THBOOK=ON ..
cmake --build .
```

**Comment by RadostW** [comment]
Thanks! Is this procedure described somewhere inside the repository?

**Comment by Afforix** [comment]
Sure, you must call the commands from the root of the project. Build steps are documented in the Appendix section of the `thbook`, available for download on the project's website: https://therion.speleo.sk/download.php.
