### ISSUE TITLE
Asking permission to publish therion on flathub

### ISSUE THREAD

**Issue by nbenitez** [therion/therion#562]
Hi Therion developers,

[Flathub](https://flathub.org/) is a build and distribution platform for Linux apps, packaged in
a way that makes them portable and running on all major distributions.
Anyone can submit an app (we're not doing it for profit), but one of the
requirements is to reach out to the application's authors if they would
like to help with maintenance and thus making that distribution channel
considered official.

I'm volunteering to make a flatpak for **therion** to be published in https://flathub.org/.

The usual maintenance for new releases is just changing version string and
the file checksum. The rest is done by flathub's build infraestructure.

It's understandable if you can't commit to maintaining it, I can do the new
version updates as needed, but we'd like to know if you are not against
distributing it on Flathub in general.

Thank you,
Nelson

**Comment by mbudaj** [comment]
Hi, 
thank you for volunteering to do this, we have no objections at all.
Martin

**Comment by nbenitez** [comment]
Thanks!
