### ISSUE TITLE
Problem with PDF

### ISSUE THREAD

**Issue by Simon-Bedoire** [therion/therion#564]
Hi,
Sorry my english is not very good...
I am currently surveying a lava tube on Reunion Island.

After the addition of my last topo session when I compile I have my lines and my points do not appear on my PDF there are only my stations.
And I can't find the reason for the bug, therion while compiling it tells me OK...

On the other hand I have the impression that during loops when the skeleton (.xvi) moves but my scraps do not follow.

I've been searching for several days now and I'm still stuck... That's why I'm asking for help..

If you can help me out or give me a contact that could help me that would be great.

Thanks in advance.

Good day

Files : thconfig / th / th2
[envoi aide.zip](https://github.com/therion/therion/files/14598081/envoi.aide.zip)

**Comment by akozhenkov** [comment]
Hi Simon,

You need to change the way  your scraps are read by therion.

Firstly add 
   input "2007.th2"
   input "2007-coupe.th2"
lines to your 2007.th file right after _survey_ line and remove coresponding _sourse_ lines from thconfig.

Then you need to make sure all _"_  in team lines are properly closed. 

And finally  _-station-names "" "@2007"_ text need to be removed from scrap definitions in .th2 files.
After that everything should work.

Cheers,
Andrey

**Comment by Simon-Bedoire** [comment]
Thank you so much.
It work.
Simon
