### ISSUE TITLE
Importing team/date/... data from survex .3d file

### ISSUE THREAD

**Issue by mlubej** [therion/therion#569]
Hi!

I'm writing a .th file where I'd like to create a survey which uses the measurements from a .3d file. This all works well, my only problem is that if I create a centerline section with the dates/names, they seem to be ignored in the final produced pdf, and at the same time they don't seem to be extracted from the .3d file.

Is there any way to bypass this to get this info?

Thanks!

**Comment by rsevero** [comment]
I believe that dates and names are not included in .3d files. It has only points and lines data.

**Comment by speleo3** [comment]
Dates are included. Team names are not.
https://survex.com/docs/3dformat.htm

**Comment by mlubej** [comment]
Thank you! will close now
