### ISSUE TITLE
Import .3d doesnt not seem to import splay shots

### ISSUE THREAD

**Issue by cctrunz** [therion/therion#591]
Hi,

It seems that the compilation of an imporation of .3d files in a therion file does not export the splays that exist in the original .3d files, when exporting to sql and .3d

Is there an other way to import the .3d file that would preserve the splay data?

Here is an example of the syntaxe of the the .th and .thconfig files I run:

cavename.th file:
---------------------------------
survey cavename
import cavename.3d -surveys use
endsurvey

thconfig file:
----------------
source cavename.th
export database -o cavename.sql
export model -fmt survex -o cavename_export.3d

**Comment by speleo3** [comment]
I'm quite familiar with the 3d import code at the moment (just finished https://github.com/therion/therion/pull/585) and could try to provide a fix.

**Comment by cctrunz** [comment]
Thanks!! that would be great!!
