### ISSUE TITLE
loch failed to build on Debian 12 and on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by boveym** [therion/therion#592]
Since commit [a207692e](https://github.com/therion/therion/commit/a207692ed699086a017d7cf0e4da79371d0b522e) `loch` is failing to compile on Debian.

Make is ending with the following error message:
```
/usr/bin/ld: cannot find -lvtkpng-9.1: No such file or directory
/usr/bin/ld: cannot find -lvtkjpeg-9.1: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:214: loch] Error 1
```

This problem is impacting Debian 12 and Ubuntu 22.04 LTS.
No other distribution has been tested.

# Work around
delete the 3 lines introduced in `loch/Makefile` by commit a207692e
```
ifeq ($(VTKV9),1)
VTKLIBS += -lvtkpng$(VTKLIBSUFFIX) -lvtkjpeg$(VTKLIBSUFFIX)
endif
```

**Comment by smudrak** [comment]
Hi Michel, thanks for finding out. I will investigate this issue. The problem is that without these 3 lines, it does not compile on older distros with newer VTK. Anyway, we want to deprecate Makefiles soon.

**Comment by mbudaj** [comment]
Please use cmake, as make is deprecated for building therion.
