### ISSUE TITLE
Therion map editor: Increase the scrap drop down list

### ISSUE THREAD

**Issue by finnesand** [therion/therion#75]
Sometimes I have several scraps in a th2-file. When I want to move something to another scrap, the drop down list only shows two scraps (4 or 5 rows). 

Could the drop down list be increased to for instance 10-12 rows?

The goal is to make the drop down list easier to use (avoid scrolling) and to have an overview over the scraps in a th2 file.

![bilde](https://cloud.githubusercontent.com/assets/8087572/25050292/e8ee206c-2146-11e7-9387-7cc140daa57f.png)

**Comment by mbudaj** [comment]
Fixed in 5.4.1

**Comment by finnesand** [comment]
Works fine, thanks.
