### ISSUE TITLE
KML generation crashes

### ISSUE THREAD

**Issue by janmulder** [therion/therion#84]
KML generation for my input file crashes. A rough bisect shows that the last release working was v5.3.16. On the current master, it crashes at the following position:

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555578c2c4 in thexpmodel::export_kml_survey_file (this=0x555555e4c1a0, out=0x5555560ef130, surv=0x555555e52ea0) at thexpmodel.cxx:1957
1957            last_st = db->db1d.station_vec[survdata->leg_list.back().to.id - 1].uid - 1;
```

Some context on the input. It is a rather big (1600 stations) datafile, automatically recorded under water using a INU based device. So lots of short legs. The PDF output is generated correctly.

I can provide the input to the developer working on this when needed, and I can compile therion from source, so also able to evaluate proposed fixes.

**Comment by smudrak** [comment]
Should be fixed in f18c718.

**Comment by janmulder** [comment]
And yes, I can confirm that my original problem from 2017 is fixed in the current master.

**Comment by smudrak** [comment]
Great, thanks for feedback.
