### ISSUE TITLE
units metre causes Therion crash

### ISSUE THREAD

**Issue by CaverBruce** [therion/therion#89]
Therion requires that units tape 'metre' be spelt as 'meter', otherwise it crashes.
As one of our local luminaries wrote recently...
" And despite NZ having had the metric system for 50 years now, many still abseil into difficulty with ‘metre’ (the well-known unit of length), by writing ‘meter’ (the equally well-known instrument that measures things). So it’s the ‘re’ ending for ‘metre’ and its relatives ‘centimetre’, ‘millimetre’, and ‘kilometre’. Whereas the instrument that measures things, the device you have to take to Oz Patterson for repairs, is a ‘meter’. "
So in en(UK) and en(NZ) meter is a device that measures.  In en(US) meter is a unit of measurement.
I suggest that Therion be modified to allow both spellings (metre and meter), in much the same way as colour and color are supported.

**Comment by ojwb** [comment]
This looks like an oversight - from `thtflength.h`:

```
  {"centimeter", TT_TFU_CM},
  {"centimeters", TT_TFU_CM},
  {"centimetre", TT_TFU_CM},
  {"centimetres", TT_TFU_CM},
  {"cm", TT_TFU_CM},
  {"feet", TT_TFU_FT},
  {"feets", TT_TFU_FT},
  {"ft", TT_TFU_FT},
  {"in", TT_TFU_IN},
  {"inch", TT_TFU_IN},
  {"inches", TT_TFU_IN},
  {"m", TT_TFU_M},
  {"meter", TT_TFU_M},
  {"meters", TT_TFU_M},
  {"metres", TT_TFU_M},
  {"metric", TT_TFU_M},
  {"millimeter", TT_TFU_MM},
  {"millimeters", TT_TFU_MM},
  {"millimetre", TT_TFU_MM},
  {"millimetres", TT_TFU_MM},
  {"mm", TT_TFU_MM},
  {"yard", TT_TFU_YD},
  {"yards", TT_TFU_YD},
  {"yd", TT_TFU_YD},
```

So you're allowed to use "metres", "centimetre", "millimetre" but not "metre".

The presence of "feets" is rather odd ("feet" **is** the plural - singular would be "foot").

**Comment by CaverBruce** [comment]
Would seem sensible to swap "feets" for "foot" while you are at it, although i guess there maybe some datasets out there that might get broken.

**Comment by ojwb** [comment]
`feets` is actually documented in the manual (though a number of the units actually supported don't seem to be - the non-US spellings, "metric", and any way of writing millimetres):

```
* {\it units} = length units supported:
           meter[s], centimeter[s], inch[es], feet[s], yard[s]
           (also m, cm, in, ft, yd).
```

I felt dropping it needed more careful consideration than adding a missing alias to complete a set.

OTOH, the only people who still seem to survey in feet and inches are those from the USA and they're not going to write "feets".
