### ISSUE TITLE
  colour preview-above does not work

### ISSUE THREAD

**Issue by CaverBruce** [therion/therion#90]
colour preview-above is ineffective.  For many years I have had;
     colour preview-above [80 0 40] #magenta
in all of my projects.  Always the preview colour is black.  I have also tried   color preview-above, to no avail.
  colour preview-below [80 0 40] works just fine, if rather gaudy.

Have previously raised this issue, without much response.
https://www.mail-archive.com/therion@speleo.sk/msg03756.html
https://www.mail-archive.com/therion@speleo.sk/msg04609.html
https://www.mail-archive.com/therion@speleo.sk/msg06337.html

**Comment by tangourilla17** [comment]
Was there a workaround for this problem?  I'm getting the same behaviour and can't seem to find a way round it.

![image](https://user-images.githubusercontent.com/41994877/109160691-06da2680-776e-11eb-8583-cd3dea89db78.png)

**Comment by CaverBruce** [comment]
Ya hoo.  This is a small thing but it makes me very happy!!!
At last the colour preview statement embedded in my projects for the previous nine years works.
Now I have to select a more suitable colour!

![image](https://user-images.githubusercontent.com/19825868/109200251-4011a580-7805-11eb-9860-f2c85357ba23.png)
